[build]
    publish = "functions"
    functions = "netlify/functions"

[[redirects]]
    from = "/"
    to = "/socks5QR.html"
    status = 200

[[redirects]]
    from = "/mailapi"
    to = "/mailApi.html"
    status = 200

[[redirects]]
    from = "/mailApi"
    to = "/mailApi.html"
    status = 200

[[redirects]]
    from = "/mailcreate"
    to = "/mailCreate.html"
    status = 200

[[redirects]]
    from = "/mailCreate"
    to = "/mailCreate.html"
    status = 200

[[redirects]]
    from = "/mailmanager"
    to = "/mailManager.html"
    status = 200

[[redirects]]
    from = "/mailview"
    to = "/mailView.html"
    status = 200

[[redirects]]
    from = "/mailView"
    to = "/mailView.html"
    status = 200

[[redirects]]
    from = "/boobar"
    to = "/mailView.html"
    status = 200

[[redirects]]
    from = "/m"
    to = "/mailView.html"
    status = 200

[[redirects]]
    from = "/functions/socks5QR.html"
    to = "/socks5QR.html"
    status = 301

[[redirects]]
    from = "/functions/mailApi.html"
    to = "/mailApi.html"
    status = 301

[[redirects]]
    from = "/functions/mailCreate.html"
    to = "/mailCreate.html"
    status = 301

[[redirects]]
    from = "/functions/mailManager.html"
    to = "/mailManager.html"
    status = 301

[[redirects]]
    from = "/functions/mailView.html"
    to = "/mailView.html"
    status = 301

[[redirects]]
    from = "/functions/assets/socksQr.css"
    to = "/assets/socksQr.css"
    status = 301

[[redirects]]
    from = "/functions/assets/socksQr.js"
    to = "/assets/socksQr.js"
    status = 301

[[redirects]]
    from = "/functions/assets/mailApi.js"
    to = "/assets/mailApi.js"
    status = 301

[[redirects]]
    from = "/functions/assets/mailCreate.js"
    to = "/assets/mailCreate.js"
    status = 301

[[redirects]]
    from = "/functions/assets/mailManager.js"
    to = "/assets/mailManager.js"
    status = 301

[[redirects]]
    from = "/functions/assets/mailView.js"
    to = "/assets/mailView.js"
    status = 301
